-- Intentionally no-op.
--
-- Production must not seed a static admin account or any default password.
-- Create the first administrator through a one-time, operator-controlled
-- bootstrap process that reads credentials from the deployment secret manager.
