-- Intentionally no-op.
--
-- This migration previously updated a repo-known admin account. Static admin
-- credentials are not safe for production; rotate or remove any account that
-- was created from older seed migrations before launch.
